In [13]:
##importing the libraries
import pandas as pd
import numpy as np

In [3]:
##reaind the dataset
dataset = pd.read_excel('Real estate valuation data set.xlsx')

In [4]:
##represention of the dataset
dataset.head()

No  X1 transaction date  X2 house age  \
0   1          2012.916667          32.0   
1   2          2012.916667          19.5   
2   3          2013.583333          13.3   
3   4          2013.500000          13.3   
4   5          2012.833333           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [6]:
##columns for our our convinience
dataset.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [7]:
## we are going to drop the column No and the X1 transaction date because we dont need that (it has no use right now)
dataset.drop(['No', 'X1 transaction date'],inplace = True,axis = 1)

In [8]:
dataset.head()

X2 house age  X3 distance to the nearest MRT station  \
0          32.0                                84.87882   
1          19.5                               306.59470   
2          13.3                               561.98450   
3          13.3                               561.98450   
4           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [9]:
##basically we are redefining the dataset because the dataset which we have right now is not too big for the random weights 
## we can implement ont this weight to but the distnance between expected to right will be too much 
##so we are just converting all the answers to decimal points 
dataset['X2 house age'] = dataset['X2 house age']/100
dataset['X3 distance to the nearest MRT station'] = dataset['X3 distance to the nearest MRT station']/1000
dataset['X4 number of convenience stores'] = dataset['X4 number of convenience stores']/10
dataset['X5 latitude'] = dataset['X5 latitude']/100
dataset['X6 longitude'] = dataset['X6 longitude']/1000
dataset['Y house price of unit area'] = dataset['Y house price of unit area']/100

In [10]:
## here we are going to rename all the columns (since for my convinience we are going to read the names again and again )
dataset['X1'] = dataset['X2 house age']
dataset['X2'] = dataset['X3 distance to the nearest MRT station']
dataset['X3'] = dataset['X4 number of convenience stores']
dataset['X4'] = dataset['X5 latitude']
dataset['X5'] = dataset['X6 longitude']
dataset['Y'] = dataset['Y house price of unit area']
## we are dropthee columns because we have a copy in x1,x2 ..Xn
dataset.drop(['X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],axis =1 ,inplace = True)

In [11]:
## this is how it looks after the alterations 
dataset.head()

X1        X2   X3        X4        X5      Y
0  0.320  0.084879  1.0  0.249830  0.121540  0.379
1  0.195  0.306595  0.9  0.249803  0.121540  0.422
2  0.133  0.561984  0.5  0.249875  0.121544  0.473
3  0.133  0.561984  0.5  0.249875  0.121544  0.548
4  0.050  0.390568  0.5  0.249794  0.121542  0.431

In [22]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1:].values

In [27]:
## tthis changes is just the target clusters which clusters there data points belongs to. s
## to cluster these we are not using any clustering algorithm but based on the husing price we are forming if ther going to buy house or not 
##so when we get house price more than 0.40 we say that a person is most likey to buy the house and we take 1 as output and if its less we say 
## a person will never buy the house sincce the price is too less or too much (we did oppositer ifthe price is too muv(greater than 0.40 ))
## a peron is going to buy and if its less hes not 
changes = []
for p in y:
    if(p>0.40):
        changes.append(1)
    else:
        changes.append(0)

In [18]:
##initializing the weights
weights = np.random.uniform(size = (5,2))

In [19]:
#these are just soe random weights
##weights

array([[0.55941709, 0.13690681],
       [0.55757108, 0.12681457],
       [0.07699759, 0.50865671],
       [0.88400931, 0.17172644],
       [0.42105741, 0.34292835]])

In [32]:
##LQ is simply just as process of identifying patterns in your data points
## the algorithm for LVQ is such that 
##   weights initialization
##   find the distnce (x-w)^2
## choose the minimum weights which is neareer to the cluster and
## mover the weight to that cluster
l = []
lrate = 0.5
for i in range(10):
    
    for j in range(2):
        temporary = 0
        for k in range(5):
            ##findind sum
            temporary = temporary + (weights[k,j]-x[i,k])**2
        l.append(temporary)
    j=0
    
    if(l[0]<[1]):
        j=0
    else:
        j=1
        
    ##checking if ther math the target
    if(j==changes[i]):
        ##if yes
        for m in range(4):
            
            weights[m,j]=weights[m,j] + (lrate *(x[i,m]-weights[m,j]))
    else:
        ##else
        for m in range(4):
            weights[m,j]=weights[m,j] - (lrate *(x[i,m]-weights[m,j]))
    print('Updated weights :\n',weights)

Updated weights :
 [[ 0.55941709 -0.29793951]
 [ 0.55757108  0.22641198]
 [ 0.07699759 -0.65828359]
 [ 0.88400931 -0.01376904]
 [ 0.42105741  0.34292835]]
Updated weights :
 [[ 0.55941709 -0.05146976]
 [ 0.55757108  0.26650334]
 [ 0.07699759  0.1208582 ]
 [ 0.88400931  0.11801718]
 [ 0.42105741  0.34292835]]
Updated weights :
 [[0.55941709 0.04076512]
 [0.55757108 0.41424392]
 [0.07699759 0.3104291 ]
 [0.88400931 0.18394589]
 [0.42105741 0.34292835]]
Updated weights :
 [[0.55941709 0.08688256]
 [0.55757108 0.48811421]
 [0.07699759 0.40521455]
 [0.88400931 0.21691024]
 [0.42105741 0.34292835]]
Updated weights :
 [[0.55941709 0.06844128]
 [0.55757108 0.43934131]
 [0.07699759 0.45260728]
 [0.88400931 0.23335197]
 [0.42105741 0.34292835]]
Updated weights :
 [[ 0.55941709  0.06716192]
 [ 0.55757108 -0.42850304]
 [ 0.07699759  0.52891091]
 [ 0.88400931  0.22521271]
 [ 0.42105741  0.34292835]]
Updated weights :
 [[0.55941709 0.20608096]
 [0.55757108 0.09748503]
 [0.07699759 0.61445546]
 [0.88