In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dataset = pd.read_excel('Real estate valuation data set.xlsx')

In [4]:
dataset.head()

No  X1 transaction date  X2 house age  \
0   1          2012.916667          32.0   
1   2          2012.916667          19.5   
2   3          2013.583333          13.3   
3   4          2013.500000          13.3   
4   5          2012.833333           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [5]:
dataset.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [6]:
dataset.drop(['No', 'X1 transaction date'],axis = 1,inplace = True)

In [7]:
dataset.head()

X2 house age  X3 distance to the nearest MRT station  \
0          32.0                                84.87882   
1          19.5                               306.59470   
2          13.3                               561.98450   
3          13.3                               561.98450   
4           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [8]:
dataset.head()

X2 house age  X3 distance to the nearest MRT station  \
0          32.0                                84.87882   
1          19.5                               306.59470   
2          13.3                               561.98450   
3          13.3                               561.98450   
4           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [9]:
dataset['X2 house age'] = dataset['X2 house age']/100
dataset['X3 distance to the nearest MRT station'] = dataset['X3 distance to the nearest MRT station']/1000
dataset['X4 number of convenience stores'] = dataset['X4 number of convenience stores']/10
dataset['X5 latitude'] = dataset['X5 latitude']/100
dataset['X6 longitude'] = dataset['X6 longitude']/1000
dataset['Y house price of unit area'] = dataset['Y house price of unit area']/100



In [10]:
dataset.head()

X2 house age  X3 distance to the nearest MRT station  \
0         0.320                                0.084879   
1         0.195                                0.306595   
2         0.133                                0.561984   
3         0.133                                0.561984   
4         0.050                                0.390568   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                              1.0     0.249830      0.121540   
1                              0.9     0.249803      0.121540   
2                              0.5     0.249875      0.121544   
3                              0.5     0.249875      0.121544   
4                              0.5     0.249794      0.121542   

   Y house price of unit area  
0                       0.379  
1                       0.422  
2                       0.473  
3                       0.548  
4                       0.431

In [11]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 6 columns):
X2 house age                              414 non-null float64
X3 distance to the nearest MRT station    414 non-null float64
X4 number of convenience stores           414 non-null float64
X5 latitude                               414 non-null float64
X6 longitude                              414 non-null float64
Y house price of unit area                414 non-null float64
dtypes: float64(6)
memory usage: 19.5 KB


In [12]:
dataset['X1'] = dataset['X2 house age']
dataset['X2'] = dataset['X3 distance to the nearest MRT station']
dataset['X3'] = dataset['X4 number of convenience stores']
dataset['X4'] = dataset['X5 latitude']
dataset['X5'] = dataset['X6 longitude']
dataset['Y'] = dataset['Y house price of unit area']
dataset.drop(['X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],axis =1 ,inplace = True)


In [13]:
dataset.head()

X1        X2   X3        X4        X5      Y
0  0.320  0.084879  1.0  0.249830  0.121540  0.379
1  0.195  0.306595  0.9  0.249803  0.121540  0.422
2  0.133  0.561984  0.5  0.249875  0.121544  0.473
3  0.133  0.561984  0.5  0.249875  0.121544  0.548
4  0.050  0.390568  0.5  0.249794  0.121542  0.431

In [14]:
weights = np.random.uniform(size = (5,1))

In [15]:
bais = np.random.uniform(size = (1,1))

In [16]:
print('weights = \n{}\nbais = \n{}'.format(weights,bais))

weights = 
[[0.95158426]
 [0.68917421]
 [0.48933418]
 [0.22945783]
 [0.488346  ]]
bais = 
[[0.02884757]]


In [17]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1:].values

In [18]:
x

array([[0.32      , 0.08487882, 1.        , 0.2498298 , 0.12154024],
       [0.195     , 0.3065947 , 0.9       , 0.2498034 , 0.12153951],
       [0.133     , 0.5619845 , 0.5       , 0.2498746 , 0.12154391],
       ...,
       [0.188     , 0.3909696 , 0.7       , 0.2497923 , 0.12153986],
       [0.081     , 0.1048101 , 0.5       , 0.2496674 , 0.12154067],
       [0.065     , 0.09045606, 0.9       , 0.2497433 , 0.1215431 ]])

In [19]:
newweights = np.zeros((5,1))
newbais = np.zeros((1,1))


In [20]:
bais

array([[0.02884757]])

In [21]:
learning_rate = np.random.rand(1,1)
learning_rate = learning_rate[0,0]
learning_rate

0.3234837364094437

In [22]:
def activation_function(x):
    return (1/(1+np.exp(-x)))

In [23]:
threshold = 0.5
for i in range(len(x)):
    s = 0
    for j in range(5):
        s = s + (x[i,j]*weights[j,0])
    s = s + bais[0,0]
    ans = activation_function(s)
    d = 0
    if ans>threshold:
        d = 1
    else:
        d = 0 
    if d == y[i]:
        weights = weights
        bais = bais
    else:
        r=1
        for k in range(5):
            newweights[k,0] = learning_rate*x[i,k]*y[i]
        newbais =  learning_rate*y[i]
        weights = weights + newweights
        bais = bais + newbais
        
        
print(weights)
print(bais)
    

[[ 9.52481841]
 [40.36533023]
 [24.37149148]
 [12.93092167]
 [ 6.67015706]]
[[50.89278331]]


In [29]:
(0.195*9.52481841)+(0.306595*40.36533023)+(0.9*24.37149148)+(0.249803*12.93092167)+(0.121540*6.67015706)

40.20836425882026