In [1]:
##importing the librarries
import pandas as pd

In [2]:
import numpy as np

In [4]:
##readong the dataset
dataset = pd.read_excel('Real estate valuation data set.xlsx')

In [5]:
##showing the dataset
dataset.head()

No  X1 transaction date  X2 house age  \
0   1          2012.916667          32.0   
1   2          2012.916667          19.5   
2   3          2013.583333          13.3   
3   4          2013.500000          13.3   
4   5          2012.833333           5.0   

   X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                84.87882                               10   
1                               306.59470                                9   
2                               561.98450                                5   
3                               561.98450                                5   
4                               390.56840                                5   

   X5 latitude  X6 longitude  Y house price of unit area  
0     24.98298     121.54024                        37.9  
1     24.98034     121.53951                        42.2  
2     24.98746     121.54391                        47.3  
3     24.98746     121.54391                        54.8  
4     24.97937     121.54245                        43.1

In [6]:
dataset.columns

Index(['No', 'X1 transaction date', 'X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],
      dtype='object')

In [7]:
##since we dont need the first columns and second column so we drom that using the funtion drop 

In [8]:
dataset.drop(['No', 'X1 transaction date'],axis = 1,inplace = True)

In [9]:
dataset.head()

X2 house age  X3 distance to the nearest MRT station  \
0          32.0                                84.87882   
1          19.5                               306.59470   
2          13.3                               561.98450   
3          13.3                               561.98450   
4           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [10]:
##and our new dataset looks like the above one

In [11]:
## But still we cant implement it because we have some large values so we change the dataset to some point answer for easy calculations 

In [12]:
dataset['X2 house age'] = dataset['X2 house age']/100
dataset['X3 distance to the nearest MRT station'] = dataset['X3 distance to the nearest MRT station']/1000
dataset['X4 number of convenience stores'] = dataset['X4 number of convenience stores']/10
dataset['X5 latitude'] = dataset['X5 latitude']/100
dataset['X6 longitude'] = dataset['X6 longitude']/1000
dataset['Y house price of unit area'] = dataset['Y house price of unit area']/100



In [13]:
## and our dataset gonna look like this

In [14]:
dataset.head()

X2 house age  X3 distance to the nearest MRT station  \
0         0.320                                0.084879   
1         0.195                                0.306595   
2         0.133                                0.561984   
3         0.133                                0.561984   
4         0.050                                0.390568   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                              1.0     0.249830      0.121540   
1                              0.9     0.249803      0.121540   
2                              0.5     0.249875      0.121544   
3                              0.5     0.249875      0.121544   
4                              0.5     0.249794      0.121542   

   Y house price of unit area  
0                       0.379  
1                       0.422  
2                       0.473  
3                       0.548  
4                       0.431

In [15]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 6 columns):
X2 house age                              414 non-null float64
X3 distance to the nearest MRT station    414 non-null float64
X4 number of convenience stores           414 non-null float64
X5 latitude                               414 non-null float64
X6 longitude                              414 non-null float64
Y house price of unit area                414 non-null float64
dtypes: float64(6)
memory usage: 19.5 KB


In [16]:
## the next line of code is just the renaming of the columns  name since earlier columns name is too big

In [17]:
dataset['X1'] = dataset['X2 house age']
dataset['X2'] = dataset['X3 distance to the nearest MRT station']
dataset['X3'] = dataset['X4 number of convenience stores']
dataset['X4'] = dataset['X5 latitude']
dataset['X5'] = dataset['X6 longitude']
dataset['Y'] = dataset['Y house price of unit area']
dataset.drop(['X2 house age',
       'X3 distance to the nearest MRT station',
       'X4 number of convenience stores', 'X5 latitude', 'X6 longitude',
       'Y house price of unit area'],axis =1 ,inplace = True)


In [18]:
## and final dataset looks like this 

In [19]:
dataset.head()

X1        X2   X3        X4        X5      Y
0  0.320  0.084879  1.0  0.249830  0.121540  0.379
1  0.195  0.306595  0.9  0.249803  0.121540  0.422
2  0.133  0.561984  0.5  0.249875  0.121544  0.473
3  0.133  0.561984  0.5  0.249875  0.121544  0.548
4  0.050  0.390568  0.5  0.249794  0.121542  0.431

In [24]:
y1 = []
for x in dataset['Y']:
    if(x>0.4):
        y1.append(1)
    else:
        y1.append(0)

In [26]:
dataset['y1'] = y1

In [27]:
dataset.head()

X1        X2   X3        X4        X5      Y  y1
0  0.320  0.084879  1.0  0.249830  0.121540  0.379   0
1  0.195  0.306595  0.9  0.249803  0.121540  0.422   1
2  0.133  0.561984  0.5  0.249875  0.121544  0.473   1
3  0.133  0.561984  0.5  0.249875  0.121544  0.548   1
4  0.050  0.390568  0.5  0.249794  0.121542  0.431   1

In [30]:
## the new line formed is basically the house bought or not 1 represent bought and 0 represents didnt Buy

In [32]:
##implementation of percentrone model 1: assigning the weights 2:bais 

In [33]:
weights = np.random.uniform(size = (5,1))

In [34]:
bais = np.random.uniform(size = (1,1))

In [35]:
## our weights and bais are 

In [36]:
print('weights = \n{}\nbais = \n{}'.format(weights,bais))

weights = 
[[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais = 
[[0.22726314]]


In [46]:
## the next line of code just distinguise the dataset in two part that is x and y 
x = dataset.iloc[:,:-2].values
y = dataset.iloc[:,-1:].values

In [47]:
print(x)

[[0.32       0.08487882 1.         0.2498298  0.12154024]
 [0.195      0.3065947  0.9        0.2498034  0.12153951]
 [0.133      0.5619845  0.5        0.2498746  0.12154391]
 ...
 [0.188      0.3909696  0.7        0.2497923  0.12153986]
 [0.081      0.1048101  0.5        0.2496674  0.12154067]
 [0.065      0.09045606 0.9        0.2497433  0.1215431 ]]


In [48]:
# where the each x[i] represent each row from the dataset

In [49]:
print(y)

[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]


In [50]:
# the next line of code just set the newbais and new weights to zero so taht we'llupdate the values  

In [51]:
newweights = np.zeros((5,1))
newbais = np.zeros((1,1))


In [52]:
print('newweights',newweights)
print('newbais',newbais)

newweights [[0.]
 [0.]
 [0.]
 [0.]
 [0.]]
newbais [[0.]]


In [53]:
##learning rate is basically used for moving the weights toward the global mimima
learning_rate = np.random.rand(1,1)
learning_rate = learning_rate[0,0]
learning_rate

0.9355351262336602

In [54]:
# defining the activation function
def activation_function(x):
    return (1/(1+np.exp(-x)))

In [59]:
## the algorithm for perceptron is 
## initialize the weights
## add the weights((Xi*weightsi)+bais))
## pass through an activations function
##check for thereshoud
##give the output

threshold = 0.5
for i in range(len(x)):
    s = 0
    for j in range(5):
        ##summation
        s = s + (x[i,j]*weights[j,0])
    s = s + bais[0,0]
    ##activation function
    ans = activation_function(s)
    d = 0
    ##checkig for threshold
    if ans>threshold:
        d = 1
    else:
        d = 0 
    ##if thery are equal
    if d == y[i]:
        ##key the same weights
        weights = weights
        bais = bais
    else:
        ##update the weights
        r=1
        for k in range(5):
            newweights[k,0] = learning_rate*x[i,k]*y[i]
        newbais =  learning_rate*y[i]
        weights = weights + newweights
        bais = bais + newbais
        
        
        print('weights\n',weights)
        print('bais\n',bais)
## and the final updated weights and bais are shown


print('The final updated weights are\n',weights)
print('The final updated bais is\n',bais)

weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.2

 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]]
weights
 [[0.60330771]
 [0.45106585]
 [0.07782131]
 [0.76921846]
 [0.53001179]]
bais
 [[0.22726314]

In [64]:
d = (0.195*0.60330771+0.306595*0.45106585 +0.9*0.07782131 +0.249803*0.76921846 +0.121540*0.53001179)+bais
d = activation_function(d)
if(d>threshold):
    print(1)
else:
    print(0)

1


In [65]:
## here for th row nuber 2 wew can see finally we are getting the output as 1 so our predicted  weights are correct

dataset.head()

X1        X2   X3        X4        X5      Y  y1
0  0.320  0.084879  1.0  0.249830  0.121540  0.379   0
1  0.195  0.306595  0.9  0.249803  0.121540  0.422   1
2  0.133  0.561984  0.5  0.249875  0.121544  0.473   1
3  0.133  0.561984  0.5  0.249875  0.121544  0.548   1
4  0.050  0.390568  0.5  0.249794  0.121542  0.431   1